apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: gcr.io/google_containers/hyperkube:{{ salt['pillar.get']('k8s_cluster:k8s_version') }}
    command:
    - /hyperkube
    - scheduler
    - --master=http://127.0.0.1:{{ salt['pillar.get']('k8s_cluster:apiserver:insecure-port') }}
    - --leader-elect=true
    resources:
      requests:
        cpu: 100m
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 15
