apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    prototype: 2-A
    id: P1
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  nodeSelector:
    id: N1
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    prototype: 2-A
    id: S1
spec:
  ports:
  - port: 80
  selector:
    id: P1
