apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    prototype: 1-B
    id: P2
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  nodeSelector:
    id: N2
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    prototype: 1-B
    id: S2
spec:
  ports:
  - port: 80
  selector:
    id: P2
